### ISSUE TITLE
build without OPENEXR

### ISSUE THREAD

**Issue by fewo** [tunabrain/tungsten#13]
in ImageIO.cpp
OPENEXR_AVAILABLE always 1 regardless of cmake.
the define should be removed ...
```c++
#define OPENEXR_AVAILABLE 1

#if OPENEXR_AVAILABLE
#include <ImfChannelList.h>
#include <ImfOutputFile.h>
#include <ImfInputFile.h>
#include <half.h>
#endif
```

**Comment by tunabrain** [comment]
Ooops! That should not have been committed. Thanks for catching that.
