### ISSUE TITLE
VS2013 Issues

### ISSUE THREAD

**Issue by ddiakopoulos** [tunabrain/tungsten#2]
tungsten\src\thirdparty\embree\geometry\virtual_object_intersector8.h(33): error C2719: 'valid': formal parameter with __declspec(align('32')) won't be aligned

Issue with Embree. Missing a define or a flag somewhere? 

---
    
https://github.com/tunabrain/tungsten/blob/facbede6ba6dbdab3c45a59bd4f381df1ae2154e/src/thirdparty/embree/simd/avx.h 

is also an issue because it can't find fmaintrin.h

---

    2>c:\engineering\opensource\tungsten\src\core\sse\SimdFloat.hpp(248): error C2144: syntax error : 'float' should be preceded by ';'
    2>c:\engineering\opensource\tungsten\src\core\sse\SimdFloat.hpp(248): error C3861: 'alignas': identifier not found

http://msdn.microsoft.com/en-us/library/hh567368.aspx alignas is not implemented in VS according to that

**Comment by warmist** [comment]
Disabling AVX in cmake helped in my case. Strangely it did not happen automatically.

**Comment by tunabrain** [comment]
To fix #6, AVX is now disabled by default. That should take care of this issue as well.
