### ISSUE TITLE
issue compiling the code

### ISSUE THREAD

**Issue by yanko** [tunabrain/tungsten#20]
I just wanted to test it out... installed qt4 and glew..opengl was there... tried compiling and get the bellow...am I missing something?

Error	33	error C2864: 'Tungsten::PreviewWindow::Fov' : a static data member with an in-class initializer must have non-volatile const integral type	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\PreviewWindow.hpp	57	1	editor
Error	34	error C2864: 'Tungsten::PreviewWindow::Near' : a static data member with an in-class initializer must have non-volatile const integral type	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\PreviewWindow.hpp	58	1	editor
Error	35	error C2864: 'Tungsten::PreviewWindow::Far' : a static data member with an in-class initializer must have non-volatile const integral type	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\PreviewWindow.hpp	59	1	editor
Error	36	error C2797: 'Tungsten::PreviewWindow::DefaultPriorities': list initialization inside member initializer list or non-static data member initializer is not implemented	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\PreviewWindow.hpp	67	1	editor
Error	40	error C2065: 'uint8_t' : undeclared identifier	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\opengl\Texture.cpp	279	1	editor
Error	41	error C2059: syntax error : ')'	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\opengl\Texture.cpp	279	1	editor
Error	50	error C2864: 'Tungsten::PreviewWindow::Fov' : a static data member with an in-class initializer must have non-volatile const integral type	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\PreviewWindow.hpp	57	1	editor
Error	51	error C2864: 'Tungsten::PreviewWindow::Near' : a static data member with an in-class initializer must have non-volatile const integral type	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\PreviewWindow.hpp	58	1	editor
Error	52	error C2864: 'Tungsten::PreviewWindow::Far' : a static data member with an in-class initializer must have non-volatile const integral type	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\PreviewWindow.hpp	59	1	editor
Error	53	error C2797: 'Tungsten::PreviewWindow::DefaultPriorities': list initialization inside member initializer list or non-static data member initializer is not implemented	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\PreviewWindow.hpp	67	1	editor
Error	54	error C2734: 'Tungsten::PreviewWindow::Fov' : const object must be initialized if not extern	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\PreviewWindow.cpp	22	1	editor
Error	55	error C2734: 'Tungsten::PreviewWindow::Near' : const object must be initialized if not extern	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\PreviewWindow.cpp	23	1	editor
Error	56	error C2734: 'Tungsten::PreviewWindow::Far' : const object must be initialized if not extern	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\PreviewWindow.cpp	24	1	editor
Error	57	error C2143: syntax error : missing ';' before '}'	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\PreviewWindow.cpp	38	1	editor
Error	58	error C2143: syntax error : missing ';' before '}'	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\PreviewWindow.cpp	44	1	editor
Error	59	error C2039: 'function' : is not a member of 'std'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	40	1	editor
Error	60	error C2061: syntax error : identifier 'function'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	40	1	editor
Error	61	error C2039: 'function' : is not a member of 'std'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	41	1	editor
Error	62	error C2061: syntax error : identifier 'function'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	41	1	editor
Error	63	error C2039: 'function' : is not a member of 'std'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	42	1	editor
Error	64	error C2061: syntax error : identifier 'function'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	42	1	editor
Error	65	error C2039: 'function' : is not a member of 'std'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	44	1	editor
Error	66	error C2061: syntax error : identifier 'function'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	44	1	editor
Error	67	error C2039: 'function' : is not a member of 'std'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	46	1	editor
Error	68	error C2061: syntax error : identifier 'function'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	46	1	editor
Error	69	error C2039: 'function' : is not a member of 'std'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	49	1	editor
Error	70	error C2061: syntax error : identifier 'function'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	49	1	editor
Error	71	error C2039: 'function' : is not a member of 'std'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	51	1	editor
Error	72	error C2061: syntax error : identifier 'function'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	51	1	editor
Error	73	error C2039: 'function' : is not a member of 'std'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	53	1	editor
Error	74	error C2061: syntax error : identifier 'function'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	53	1	editor
Error	75	error C2039: 'function' : is not a member of 'std'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	55	1	editor
Error	76	error C2061: syntax error : identifier 'function'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	55	1	editor
Error	77	error C2039: 'function' : is not a member of 'std'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	57	1	editor
Error	78	error C2061: syntax error : identifier 'function'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	57	1	editor
Error	79	error C2039: 'function' : is not a member of 'std'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	59	1	editor
Error	80	error C2061: syntax error : identifier 'function'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	59	1	editor
Error	81	error C2660: 'Tungsten::PropertySheet::addBsdfProperty' : function does not take 5 arguments	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\BsdfProperties.cpp	14	1	editor
Error	88	error C2039: 'function' : is not a member of 'std'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	40	1	editor
Error	89	error C2061: syntax error : identifier 'function'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	40	1	editor
Error	90	error C2039: 'function' : is not a member of 'std'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	41	1	editor
Error	91	error C2061: syntax error : identifier 'function'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	41	1	editor
Error	92	error C2039: 'function' : is not a member of 'std'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	42	1	editor
Error	93	error C2061: syntax error : identifier 'function'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	42	1	editor
Error	94	error C2039: 'function' : is not a member of 'std'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	44	1	editor
Error	95	error C2061: syntax error : identifier 'function'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	44	1	editor
Error	96	error C2039: 'function' : is not a member of 'std'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	46	1	editor
Error	97	error C2061: syntax error : identifier 'function'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	46	1	editor
Error	98	error C2039: 'function' : is not a member of 'std'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	49	1	editor
Error	99	error C2061: syntax error : identifier 'function'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	49	1	editor
Error	100	error C2039: 'function' : is not a member of 'std'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	51	1	editor
Error	101	error C2061: syntax error : identifier 'function'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	51	1	editor
Error	102	error C2039: 'function' : is not a member of 'std'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	53	1	editor
Error	103	error C2061: syntax error : identifier 'function'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	53	1	editor
Error	104	error C2039: 'function' : is not a member of 'std'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	55	1	editor
Error	105	error C2061: syntax error : identifier 'function'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	55	1	editor
Error	106	error C2039: 'function' : is not a member of 'std'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	57	1	editor
Error	107	error C2061: syntax error : identifier 'function'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	57	1	editor
Error	108	error C2039: 'function' : is not a member of 'std'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	59	1	editor
Error	109	error C2061: syntax error : identifier 'function'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	59	1	editor
Error	110	error C2660: 'Tungsten::PropertySheet::addStringProperty' : function does not take 3 arguments	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PrimitiveProperties.cpp	15	1	editor
Error	111	error C2660: 'Tungsten::PropertySheet::addTextureProperty' : function does not take 6 arguments	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PrimitiveProperties.cpp	21	1	editor
Error	112	error C2660: 'Tungsten::PropertySheet::addMediumProperty' : function does not take 4 arguments	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PrimitiveProperties.cpp	25	1	editor
Error	113	error C2660: 'Tungsten::PropertySheet::addMediumProperty' : function does not take 4 arguments	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PrimitiveProperties.cpp	29	1	editor
Error	114	error C2039: 'function' : is not a member of 'std'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	40	1	editor
Error	115	error C2061: syntax error : identifier 'function'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	40	1	editor
Error	116	error C2039: 'function' : is not a member of 'std'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	41	1	editor
Error	117	error C2061: syntax error : identifier 'function'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	41	1	editor
Error	118	error C2039: 'function' : is not a member of 'std'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	42	1	editor
Error	119	error C2061: syntax error : identifier 'function'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	42	1	editor
Error	120	error C2039: 'function' : is not a member of 'std'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	44	1	editor
Error	121	error C2061: syntax error : identifier 'function'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	44	1	editor
Error	122	error C2039: 'function' : is not a member of 'std'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	46	1	editor
Error	123	error C2061: syntax error : identifier 'function'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	46	1	editor
Error	124	error C2039: 'function' : is not a member of 'std'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	49	1	editor
Error	125	error C2061: syntax error : identifier 'function'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	49	1	editor
Error	126	error C2039: 'function' : is not a member of 'std'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	51	1	editor
Error	127	error C2061: syntax error : identifier 'function'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	51	1	editor
Error	128	error C2039: 'function' : is not a member of 'std'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	53	1	editor
Error	129	error C2061: syntax error : identifier 'function'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	53	1	editor
Error	130	error C2039: 'function' : is not a member of 'std'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	55	1	editor
Error	131	error C2061: syntax error : identifier 'function'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	55	1	editor
Error	132	error C2039: 'function' : is not a member of 'std'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	57	1	editor
Error	133	error C2061: syntax error : identifier 'function'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	57	1	editor
Error	134	error C2039: 'function' : is not a member of 'std'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	59	1	editor
Error	135	error C2061: syntax error : identifier 'function'	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.hpp	59	1	editor
Error	136	error C2511: 'Tungsten::BoolProperty *Tungsten::PropertySheet::addBoolProperty(int,std::string,std::function<bool (bool)>)' : overloaded member function not found in 'Tungsten::PropertySheet'	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	25	1	editor
Error	137	error C2597: illegal reference to non-static member 'Tungsten::PropertySheet::_parent'	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	26	1	editor
Error	138	error C2671: 'Tungsten::PropertySheet::addBoolProperty' : static member functions do not have 'this' pointers	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	26	1	editor
Error	139	error C2228: left of '.emplace_back' must have class/struct/union	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	27	1	editor
Error	140	error C2511: 'Tungsten::IntProperty *Tungsten::PropertySheet::addIntProperty(int,int,int,std::string,std::function<bool (int)>)' : overloaded member function not found in 'Tungsten::PropertySheet'	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	32	1	editor
Error	141	error C2597: illegal reference to non-static member 'Tungsten::PropertySheet::_parent'	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	33	1	editor
Error	142	error C2671: 'Tungsten::PropertySheet::addIntProperty' : static member functions do not have 'this' pointers	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	33	1	editor
Error	143	error C2228: left of '.emplace_back' must have class/struct/union	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	34	1	editor
Error	144	error C2511: 'Tungsten::FloatProperty *Tungsten::PropertySheet::addFloatProperty(float,std::string,std::function<bool (float)>)' : overloaded member function not found in 'Tungsten::PropertySheet'	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	39	1	editor
Error	145	error C2597: illegal reference to non-static member 'Tungsten::PropertySheet::_parent'	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	40	1	editor
Error	146	error C2671: 'Tungsten::PropertySheet::addFloatProperty' : static member functions do not have 'this' pointers	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	40	1	editor
Error	147	error C2228: left of '.emplace_back' must have class/struct/union	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	41	1	editor
Error	148	error C2511: 'Tungsten::VectorProperty *Tungsten::PropertySheet::addVectorProperty(Tungsten::Vec3f,std::string,bool,std::function<bool (Tungsten::Vec3f)>)' : overloaded member function not found in 'Tungsten::PropertySheet'	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	47	1	editor
Error	149	error C2597: illegal reference to non-static member 'Tungsten::PropertySheet::_parent'	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	48	1	editor
Error	150	error C2671: 'Tungsten::PropertySheet::addVectorProperty' : static member functions do not have 'this' pointers	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	48	1	editor
Error	151	error C2228: left of '.emplace_back' must have class/struct/union	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	49	1	editor
Error	152	error C2511: 'Tungsten::StringProperty *Tungsten::PropertySheet::addStringProperty(std::string,std::string,std::function<bool (const std::string &)>)' : overloaded member function not found in 'Tungsten::PropertySheet'	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	54	1	editor
Error	153	error C2597: illegal reference to non-static member 'Tungsten::PropertySheet::_parent'	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	55	1	editor
Error	154	error C2671: 'Tungsten::PropertySheet::addStringProperty' : static member functions do not have 'this' pointers	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	55	1	editor
Error	155	error C2228: left of '.emplace_back' must have class/struct/union	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	57	1	editor
Error	156	error C2511: 'Tungsten::PathProperty *Tungsten::PropertySheet::addPathProperty(std::string,std::string,std::string,std::string,std::string,std::function<bool (const std::string &)>)' : overloaded member function not found in 'Tungsten::PropertySheet'	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	64	1	editor
Error	157	error C2597: illegal reference to non-static member 'Tungsten::PropertySheet::_parent'	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	65	1	editor
Error	158	error C2671: 'Tungsten::PropertySheet::addPathProperty' : static member functions do not have 'this' pointers	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	65	1	editor
Error	159	error C2228: left of '.emplace_back' must have class/struct/union	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	68	1	editor
Error	160	error C2511: 'Tungsten::ListProperty *Tungsten::PropertySheet::addListProperty(std::vector<std::string,std::allocator<_Ty>>,std::string,std::string,std::function<bool (const std::string &,int)>)' : overloaded member function not found in 'Tungsten::PropertySheet'	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	74	1	editor
Error	161	error C2597: illegal reference to non-static member 'Tungsten::PropertySheet::_parent'	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	75	1	editor
Error	162	error C2671: 'Tungsten::PropertySheet::addListProperty' : static member functions do not have 'this' pointers	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	75	1	editor
Error	163	error C2228: left of '.emplace_back' must have class/struct/union	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	77	1	editor
Error	164	error C2511: 'Tungsten::ListProperty *Tungsten::PropertySheet::addListProperty(std::vector<std::string,std::allocator<_Ty>>,int,std::string,std::function<bool (const std::string &,int)>)' : overloaded member function not found in 'Tungsten::PropertySheet'	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	83	1	editor
Error	165	error C2597: illegal reference to non-static member 'Tungsten::PropertySheet::_parent'	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	84	1	editor
Error	166	error C2671: 'Tungsten::PropertySheet::addListProperty' : static member functions do not have 'this' pointers	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	84	1	editor
Error	167	error C2228: left of '.emplace_back' must have class/struct/union	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	86	1	editor
Error	168	error C2511: 'Tungsten::TextureProperty *Tungsten::PropertySheet::addTextureProperty(std::shared_ptr<Tungsten::Texture>,std::string,bool,Tungsten::Scene *,Tungsten::TexelConversion,std::function<bool (std::shared_ptr<Tungsten::Texture> &)>)' : overloaded member function not found in 'Tungsten::PropertySheet'	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	93	1	editor
Error	169	error C2597: illegal reference to non-static member 'Tungsten::PropertySheet::_parent'	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	94	1	editor
Error	170	error C2671: 'Tungsten::PropertySheet::addTextureProperty' : static member functions do not have 'this' pointers	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	94	1	editor
Error	171	error C2228: left of '.emplace_back' must have class/struct/union	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	96	1	editor
Error	172	error C2511: 'Tungsten::BsdfProperty *Tungsten::PropertySheet::addBsdfProperty(std::shared_ptr<Tungsten::Bsdf>,std::string,bool,Tungsten::Scene *,std::function<bool (std::shared_ptr<Tungsten::Bsdf> &)>)' : overloaded member function not found in 'Tungsten::PropertySheet'	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	102	1	editor
Error	173	error C2597: illegal reference to non-static member 'Tungsten::PropertySheet::_parent'	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	103	1	editor
Error	174	error C2671: 'Tungsten::PropertySheet::addBsdfProperty' : static member functions do not have 'this' pointers	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	103	1	editor
Error	175	error C2228: left of '.emplace_back' must have class/struct/union	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	104	1	editor
Error	176	error C2511: 'Tungsten::MediumProperty *Tungsten::PropertySheet::addMediumProperty(std::shared_ptr<Tungsten::Medium>,std::string,Tungsten::Scene *,std::function<bool (std::shared_ptr<Tungsten::Medium> &)>)' : overloaded member function not found in 'Tungsten::PropertySheet'	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	110	1	editor
Error	177	error C2597: illegal reference to non-static member 'Tungsten::PropertySheet::_parent'	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	111	1	editor
Error	178	error C2671: 'Tungsten::PropertySheet::addMediumProperty' : static member functions do not have 'this' pointers	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	111	1	editor
Error	179	error C2228: left of '.emplace_back' must have class/struct/union	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\src\editor\properties\PropertySheet.cpp	112	1	editor
Error	183	error C2864: 'Tungsten::PreviewWindow::Fov' : a static data member with an in-class initializer must have non-volatile const integral type	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\PreviewWindow.hpp	57	1	editor
Error	184	error C2864: 'Tungsten::PreviewWindow::Near' : a static data member with an in-class initializer must have non-volatile const integral type	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\PreviewWindow.hpp	58	1	editor
Error	185	error C2864: 'Tungsten::PreviewWindow::Far' : a static data member with an in-class initializer must have non-volatile const integral type	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\PreviewWindow.hpp	59	1	editor
Error	186	error C2797: 'Tungsten::PreviewWindow::DefaultPriorities': list initialization inside member initializer list or non-static data member initializer is not implemented	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\PreviewWindow.hpp	67	1	editor
Error	191	error C2864: 'Tungsten::PreviewWindow::Fov' : a static data member with an in-class initializer must have non-volatile const integral type	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\PreviewWindow.hpp	57	1	editor
Error	192	error C2864: 'Tungsten::PreviewWindow::Near' : a static data member with an in-class initializer must have non-volatile const integral type	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\PreviewWindow.hpp	58	1	editor
Error	193	error C2864: 'Tungsten::PreviewWindow::Far' : a static data member with an in-class initializer must have non-volatile const integral type	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\PreviewWindow.hpp	59	1	editor
Error	194	error C2797: 'Tungsten::PreviewWindow::DefaultPriorities': list initialization inside member initializer list or non-static data member initializer is not implemented	c:\users\jpetrovic\downloads\tungsten-master\tungsten-master\src\editor\PreviewWindow.hpp	67	1	editor

**Comment by tunabrain** [comment]
Oh, interesting. This looks like MSVC, is that correct?

I never actually tested the MSVC build of the editor, so there may be some issues that are not present with other compilers. I'll try to get a Windows build of Qt going and will have a look on the weekend. In the meantime, you can try reconfiguring without Qt, since the rest of the renderer should hopefully work fine (although it's CLI only then).

**Comment by yanko** [comment]
Yes it is the ms vs 2013 community ed. 
do you have any scene in json? could not find any, and am not sure what is the format needed s oI can write my own..

tx.

**Comment by tunabrain** [comment]
data/materialtest/materialtest.json contains a simple example scene with the Tungsten material test ball. There is unfortunately no documentation yet, but uploading more example scenes is a good idea. I will put it on the list and hopefully prepare some scenes on the weekend.

**Comment by yanko** [comment]
was able to run Tungsten with the materialtest, it took 17 mins(older mac2011 running bootcamp...)
will try this weekend my home machine. but it's really nice! 
let me know about the editor...

thankx dude.
![tungstenrender](https://cloud.githubusercontent.com/assets/989666/8751733/f7ddf220-2c7c-11e5-8a8c-f35396bd4995.png)

**Comment by tunabrain** [comment]
Hi,

I fixed the editor to compile with MSVC. I was only able to test with a 32bit build of Qt, but hopefully 64bit will now compile as well. Let me know whether that fixes it for you.

I also started adding a few example scenes to `data/example-scenes` (more to come, hopefully).

The image you linked looks correct, but the runtime is a bit concerning - the material test should normally take about 20 seconds to render. Did you render with a debug build by any chance?

**Comment by yanko** [comment]
will give it a try today, for the editor.
tx for the examples.

and yes, I run it in debug mode. so it's fine, plus it's older machine(radeon HD 6490M 256mb gram)

**Comment by yanko** [comment]
Hi,
so I had to complie in win32, I get this if win64
Error	42	error LNK1112: module machine type 'X86' conflicts with target machine type 'x64'	C:\Users\jpetrovic\Downloads\tungsten-master\tungsten-master\vstudio\QtOpenGLd4.lib(QtOpenGLd4.dll)	editor

could not test the editor yet, since it's asking me for a bunch of dlls...the glew and qt dlls...
but it compiles so that is good.

thank you.

**Comment by tunabrain** [comment]
It seems like the original issue is resolved. Let me know if you want to reopen.
