### ISSUE TITLE
Example Scene

### ISSUE THREAD

**Issue by fycus-tree** [tunabrain/tungsten#22]
Is there any documentation on re-rendering the example scene shown in Header.jpg ?

**Comment by tunabrain** [comment]
Hi,

The museum scene in Header.jpg is not publicly available at this point. It also predates much of the renderer, and the scene file is no longer compatible.

Cheers,
Benedikt

**Comment by leonidk** [comment]
What about one of the other test scenes in your report (e.g. the blender scenes) ?

**Comment by fycus-tree** [comment]
What about some of the other test scenes in your report (e.g. the blender scenes?)?

Thanks

**Comment by tunabrain** [comment]
Some example scenes are in the repo - the material test ball from the report is in `data/materialtest/materialtest.json`, and there are a few other scenes in `data/example-scenes`. I'm currently working on releasing a few more example scenes to better demonstrate different features of the renderer, but this might take a while (holidays :) ).

**Comment by fycus-tree** [comment]
Is there any clear method or technique for exporting for blender and reproducing some of your other results from your report? I tried the blender-tungsten plugin and the lighting seems to always get garbled in the translation and produce an unusable white/black noise scene.

**Comment by tunabrain** [comment]
I usually export to OBJ and then use obj2json to generate a Tungsten scene from that. Then I setup lighting and materials using the scene editor.

I'm not involved with the blender-tungsten plugin, but I believe it hasn't been updated in a while and may no longer be compatible with the scene format.
