### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [tunabrain/tungsten#27]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for NULL before delete p?") like the following.
* [BsdfProperty::buildBsdfPage](https://github.com/tunabrain/tungsten/blob/fd795e1c62d2a1630070a87f7ec314d334fdad84/src/editor/properties/BsdfProperty.cpp#L208 "BsdfProperty::buildBsdfPage function")
* [Permutation](https://github.com/tunabrain/tungsten/blob/fd795e1c62d2a1630070a87f7ec314d334fdad84/src/thirdparty/embree/math/permutation.h#L50 "Destructor for Permutation")

**Comment by tunabrain** [comment]
Hi!

One of these is in embree, which is a third-party library that I would prefer not to change. I'm not too comfortable removing the null pointer check in the first example, as I faintly remember a reason for it being there.

Thanks!
