### ISSUE TITLE
Motion Blur

### ISSUE THREAD

**Issue by crydalch** [tunabrain/tungsten#30]
Looking around the repo, it looks like there is motion blur support in embree, but tungsten doesn't support motion blur itself, right? Is that planned?

Wonderful renderer, thank you for sharing it!

**Comment by tunabrain** [comment]
You're right, currently there's no motion blur support in Tungsten. It is on the roadmap, but currently I'm gearing up for the first proper release of tungsten, which means working more on making the software stable. After the first release I'll start thinking about adding new features.

Thanks for the comment! Hope it helps.
