### ISSUE TITLE
Regarding the final project report on the CGL competition web page

### ISSUE THREAD

**Issue by mmmovania** [tunabrain/tungsten#32]
From your readme, you mentioned that there is a final project report on the project on the competition page but it is not accessible (CGL server gives a 404 error). If possible, could you please share the local copy of that final project report. Right now it is hard to figure out how to go about this project as there is no documentation.

**Comment by tunabrain** [comment]
It looks like CGL has some domain issues. While that is resolved, here's an online copy from my website:
https://benedikt-bitterli.me/is-report/index.html

Documentation is in the works.

**Comment by mmmovania** [comment]
Thanks a million for sharing your work both for this project as well as incremental fluids. Both are invaluable assets.
