### ISSUE TITLE
cannot find core.lib

### ISSUE THREAD

**Issue by eslamsoka** [tunabrain/tungsten#36]
hi 
this is the error show when i try to build with vs2013
cannot find core.lib

**Comment by tunabrain** [comment]
There were some brief MSVC compilation issues on the latest commit. I have since fixed them. Can you try again with the latest commit? Thanks!

**Comment by eslamsoka** [comment]
sorry i cant understand you 
you mean try to download again and try it or try it on  another version of MSVC
i used MSVC  013

**Comment by tunabrain** [comment]
Redownloading the code base (and using the same MSVC) should work. I tried it today on MSVC and it works fine. 

Thanks!
Benedikt
