### ISSUE TITLE
Tungsten server no longer working

### ISSUE THREAD

**Issue by s5rockhoppers** [tunabrain/tungsten#40]
The server portion of tungsten is no longer working with the new release. The regular ex3cutable does but when trying to run the server it crashes.

**Comment by eminence** [comment]
What OS/version are you using?

**Comment by s5rockhoppers** [comment]
I'm on Windows 7, 64-bit. Using the --help command line argument works, it just crashes when going into the actual render. Using the same scene file with the normal binary (tungsten.exe) works fine.

**Comment by s5rockhoppers** [comment]
If I compile it myself (on a Windows 7 32-bit machine) then it works. I don't have all the dependencies set up through so it is missing several features.

**Comment by tunabrain** [comment]
Thanks for reporting this. There was a linking issue in civetweb that interfered with the native pthread implementation. The latest release should fix this issue.
