### ISSUE TITLE
Tungsten.exe crash when starting

### ISSUE THREAD

**Issue by goofoo** [tunabrain/tungsten#41]
Tungsten.exe crash when starting - all time.

Maybe this help.
Exception thrown at 0x00000000005C543E in tungsten.exe: 0xC000001D: Illegal Instruction.
Unhandled exception at 0x00000000005C543E in tungsten.exe: 0xC000001D: Illegal Instruction.

00000000005C543E  shrx        rax,qword ptr [rcx+10h],rax 

Windows 7 x64

**Comment by CounterPillow** [comment]
On what CPU is this? It's possible that it's missing one of the required SIMD instruction sets.

**Comment by goofoo** [comment]
CPU i7-3770K. This problem only on v0.2.0 and 0.2.1. Release 0.1.0 - work good

**Comment by tunabrain** [comment]
It looks like your CPU architecture is older than the one I compiled on, and the tungsten release uses a SIMD instruction not supported by your architecture.

I recompiled the release targeting an older Intel architecture, this should fix the issue for you. Just redownload the latest version of the 0.2.1 release:
https://github.com/tunabrain/tungsten/releases/tag/v0.2.1

**Comment by goofoo** [comment]
Cool. Now working.
Thanks Benedikt.
