### ISSUE TITLE
No optimization for Intel Core i7-7700 CPU

### ISSUE THREAD

**Issue by chaosink** [tunabrain/tungsten#43]
```
CMake Warning at cmake/OptimizeForArchitecture.cmake:117 (message):
  Your CPU (family 6, model 158) is not known.  Auto-detection of
  optimization flags failed and will use the 65nm Core 2 CPU settings.
```
The optimization file `tungsten/cmake/OptimizeForArchitecture.cmake` need to be updated.
The newest version: [OptimizeForArchitecture.cmake](https://github.com/VcDevel/Vc/blob/master/cmake/OptimizeForArchitecture.cmake)

Acturally I have tried to update the file but encountered some problems...

**Comment by tunabrain** [comment]
I just pushed a commit with an updated version of OptimizeForArchitecture. This should (hopefully) fix your problem.

Thanks!
Benedikt
