### ISSUE TITLE
Is there a way to disable rendering the infinite_sphere when using it purely as a lightsource?

### ISSUE THREAD

**Issue by saliksyed** [tunabrain/tungsten#46]
I'm trying to render an object with the environment map for lighting but want to keep a black background. Is there any way to do this?

**Comment by tunabrain** [comment]
You can set min_bounces to 1, which will disable directly visible light sources (including the envmap).
This will usually do what you want. Note however that this is global - if you have some other light source in the scene, it will also turn black.

**Comment by saliksyed** [comment]
This worked perfectly. Thank You!
