### ISSUE TITLE
Variance computation

### ISSUE THREAD

**Issue by chaosink** [tunabrain/tungsten#48]
I saw the [variance computation code](https://github.com/tunabrain/tungsten/blob/9faf4662cec247d4c72836880d7048103340c039/src/core/cameras/OutputBuffer.hpp#L182).

```
scaled[i] = _variance[i]/T(_sampleCount[i]*max(uint32(1), _sampleCount[i] - 1));
```

The variance is divided by spp additionally. Is that intentional considering the variable name is `scaled`?

**Comment by tunabrain** [comment]
In rendering, "variance" has two different meanings - it is either the sample variance of a set of samples, or the variance of the _mean_ of the samples. If there are N samples, then the sample variance would be obtained by dividing by (N-1). If you want the variance of the sample mean, then you need to divide by N*(N-1).

In Tungsten and its denoiser, I always deal with the variance of the sample mean, hence the division by N*(N-1). This is intended.
