### ISSUE TITLE
./setup_builds.sh: 5: ./setup_builds.sh: Syntax error: "(" unexpected (expecting "fi")

### ISSUE THREAD

**Issue by ivanceras** [tunabrain/tungsten#5]
I'm having an issue running the setup with linux ubuntu 14.04

```sh
./setup_builds.sh: 5: ./setup_builds.sh: Syntax error: "(" unexpected (expecting "fi")
```

I'm presume this could be shell syntax. I've tried poking the shell syntax code but to no avail.

**Comment by tunabrain** [comment]
The issue was most likely an inproper shebang.

Did the latest commit fix it for you?

**Comment by ivanceras** [comment]
Yes, the last commit fix it. However the make command encounter a new error on this issue here https://github.com/tunabrain/tungsten/issues/6
