### ISSUE TITLE
editor.exe demands qt platform on windows

### ISSUE THREAD

**Issue by 3DdeepAI** [tunabrain/tungsten#52]
A message box containing 
**"This application failed to start because it could not find or load the Qt platform plugin „windows“**
is shown. 
As some answers on other forums suggested I created a "platforms" folder and moved all the Qt*.dll files there. Then this message box disappears, but instead another one is shown containing:
**"editor.exe cannot find entry point  _ZN10QArrayData10deallocateEPS_yy" in editor.exe"**

system: Win10PRO 64bit v1607 (Anniversary Update)

**Comment by tunabrain** [comment]
I released new binaries for Windows that include the missing libraries.

Please find them here: https://github.com/tunabrain/tungsten/releases/tag/v0.2.2
