### ISSUE TITLE
Radiance scaling due to solid angle compression for light transmission

### ISSUE THREAD

**Issue by chaosink** [tunabrain/tungsten#54]
It seems that Tungsten doesn't account for this fact.

Mitsuba reference: https://github.com/mitsuba-renderer/mitsuba/blob/master/src/bsdfs/dielectric.cpp#L246

**Comment by tunabrain** [comment]
This is accounted for here:

https://github.com/tunabrain/tungsten/blob/master/src/core/bsdfs/Bsdf.hpp#L71

**Comment by chaosink** [comment]
Nice architecture! :+1:
