### ISSUE TITLE
How to get EXR image.

### ISSUE THREAD

**Issue by jaisonoh** [tunabrain/tungsten#61]
Hi. 
I am newly using tungsten renderer.
When I tested some scenes, I just got png images and option for hdr output file doesn't work.
How can I get HDR images after rendering?

Thanks.

**Comment by CounterPillow** [comment]
compile with OpenEXR support, it's auto-detected if it's installed along with its development headers on your system.

**Comment by jaisonoh** [comment]
Thanks!

**Comment by tunabrain** [comment]
To add to what CounterPillow said, if OpenEXR is not available, you can always tell Tungsten to write PFM files. These are uncompressed (and therefore larger), but they allow you to get HDR images out of Tungsten without external libraries.

There are two ways to tell Tungsten to write high dynamic range images: Either have `"output_file": "TungstenRender.exr"` in the `renderer` block of the scene file, or use -e TungstenRender.exr on the commandline.
