### ISSUE TITLE
About render elments .

### ISSUE THREAD

**Issue by 1003581** [tunabrain/tungsten#66]
Hello,

Recently, I used Tungsten to render and output the render elements（'normal','albedo','visibility','depth'）. I also used VRay to render same scene and output the render elements（here is the list of VRay supported render elements: https://docs.chaosgroup.com/display/VRAY3MAX/List+of+Supported+Render+Elements）. But I found that there is differet between Tungsten's render elments and VRay's elments. For instance , Tungsten has ‘albedo’，but VRay has not 'albedo'.
 So I want to ask that is there any connection between Tungsten's render elments and VRay's elments? In other words, can VRay's render elments be merged intoTungsten's render elments?

**Comment by tunabrain** [comment]
Output channels can vary quite a bit between renderers, and it's unlikely tungsten and vray will match up exactly, due to differences in rendering algorithms, material systems, etc.

I haven't used vray, but I believe the closest correspondence to albedo would be "VRayDiffuseFilter".
