### ISSUE TITLE
How to cite this renderer?

### ISSUE THREAD

**Issue by Enigmatisms** [tunabrain/tungsten#73]
Hi! Thank you for this great renderer! Since I've done some researches based on this repo and I've been unable to find a way to cite this repo, I wonder whether there is a BibTeX entry for this renderer, or shall I cite this repo in some other ways?

**Comment by tunabrain** [comment]
That's really great to hear! I hope it was useful. Thank you for citing - you can use the BibTeX below:

```
@misc{Bitterli:2018:Tungsten,
  title = {Tungsten Renderer},
  author = {Bitterli, Benedikt},
  year = {2018},
  url = {https://github.com/tunabrain/tungsten/}
}
```

**Comment by Enigmatisms** [comment]
Thanks!
